apiVersion: v1
kind: Pod
metadata:
  name: cdk
  namespace: default
spec:
  volumes:
  - name: cdk
    emptyDir: {}
  containers:
  - name: cdk
    image: reg.lab.uniforce.com.tw/aqua/cdk:v1
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: cdk
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: true
