apiVersion: v1
kind: Pod
metadata:
  name: fileless
  namespace: default
spec:
  volumes:
  - name: fileless
    emptyDir: {}
  containers:
  - name: fileless
    image: reg.lab.uniforce.com.tw/aqua/fileless-1:DTA
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: fileless
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: true
